### ISSUE TITLE
Support for citeproc's options

### ISSUE THREAD

**Issue by artt** [citation-js/citation-js#119]
Saw you mentioned this [here](https://github.com/larsgw/citation.js/issues/148):

> Citeproc has some other options regarding citations, including locators, prefixes, suffixes, labels and some things regarding ordering, so I can look into support for that, too.

Not sure if you have had a chance to look at this yet. I'm looking to parse something like this in markdown, but I'm not sure how to get started.

```
Blah blah [see @doe99, pp. 33-35; also @smith04, chap. 1].
Blah blah [@doe99, pp. 33-35, 38-39 and *passim*].
Blah blah [@smith04; @doe99].
```

At the very least, being able to distinguish between inline cite (`\citet` equivalent) and citing in parentheses (`\citep`) would be a great start.

Thanks!

**Comment by larsgw** [comment]
That looks cool! Citeproc-js can definitely handle pages, though I'm unsure how well it handles multiple ranges. If you want to take advantage of the built-in localization you'd want to map `pp.` to the corresponding [label](https://docs.citationstyles.org/en/stable/specification.html#locators).

Now, supporting that in Citation.js would be fairly straightforward, I think. The `entry` option is currently a list of ids, which are then converted to citeproc-js' [cite-items](https://citeproc-js.readthedocs.io/en/latest/csl-json/markup.html#cite-items). The function can be adapted to also take cite-items instead of plain ids. If you're interested, you're welcome to make a PR, otherwise I'll add it later. I was looking to support it anyway for a basic LaTeX to HTML converter so I have motive to support it quickly too.

**Comment by larsgw** [comment]
I forgot to ask, what output do you get with `\citet`? Something like "Smith (2004)" should be possible (`composite: true`) but something else might not be.

**Comment by artt** [comment]
Thanks for a fast reply!

To give you more background, I'm writing a plugin for Gatsby that would add references to markdown posts. I'd like for the web output to be consistent with what I'd get using [pandoc](https://pandoc.org/MANUAL.html#extension-citations) (so that there's only one "content" to keep around).

To tell you the truth, I'm a bit confused as to where to start with your library and I'm busy with this other project though, so would be a little while, but if you could point to where I should look, I could take a look at it and, with some time and luck, submit a PR.

> I forgot to ask, what output do you get with `\citet`? Something like "Smith (2004)" should be possible (composite: true) but something else might not be.

Right, `\citet` would be exactly that.

**Comment by timlrx** [comment]
Hi @larsgw, are you still planning to support this feature? I am looking to use citation.js for my blog and would like to have that functionality as well.

I can submit a PR to allow `entry` to be either a list of ids or a list of cite-items. On the implementation side, would you also want to include a `options.citationsPre` and `options.citationsPost` option? We can probably implement it as a list of citationIDs but not note-number pairs.

**Comment by larsgw** [comment]
Oh I see that's what they are named in citeproc-js, I won't change the names.

**Comment by larsgw** [comment]
Both support for cite-items and `citationsPre`/`citationsPost` will be included in the next release, which will likely be `v0.5.3`.

**Comment by timlrx** [comment]
I integrated `citation-js` as a rehype plugin - [rehype-citation](https://github.com/timlrx/rehype-citation). This was before your recent changes on master. Was not able to use `citation.js` directly and had to escape to `cite-proc` and `processCitationCluster` for that part. 

For some reason `previewCitationCluster` does not interact with `citationsPre` and `citationsPost` properly - it might be to do with how it prepares and update the registry, which I am not too familiar with. Those options are needed to render footnote styles correctly since the sequence of citations matter.

I still used `citation-js` for the general parsing and bibtex support so thanks for that. The CSL code was also very useful to understand how `cite-proc` works.

**Comment by larsgw** [comment]
I made a new bug report for that part. It probably does have to do with the registry, but I am not immediately sure what to do about it.
