### ISSUE TITLE
larsgw/citation.js vs citation-js/citation-js

### ISSUE THREAD

**Issue by AlexanderZeilmann** [citation-js/citation-js#129]
First of all, thank you for the great project, I really like it! 😍 

However one thing confuses me:
Why are there two repositories?
* https://github.com/larsgw/citation.js
* https://github.com/citation-js/citation-js

What is the relationship between these two repositories?
Which should I use?

**Comment by larsgw** [comment]
larsgw/citation.js used to be the main repository, containing Citation.js in a single npm module (citation-js pre 0.4.0). During the development of 0.4.0, I split it off into components which I put it in citation-js/citation-js. This has indeed been a bit confusing. larsgw/citation.js now contains a wrapper module (still citation-js) that emulates the pre-0.4.0 citation-js module but now with the separated modules from citation-js/citation-js.

As for which one to use, I would like bug reports in citation-js/citation-js but either is fine. Using the modules from citation-js/citation-js allows for finer control on which formats to include (if you're not using the CSL plugin, not including it can have the bundle size). However, the classic bundle form larsgw/citation.js may be more convenient depending on your situation, especially if you used Citation.js previous to version 0.4.0.

I am planning to move larsgw/citation.js to something like citation-js/classic and updating the README to clarify, but I have been putting it off because I'm worried I would mess the situation up even further.

I hope that clarifies things, if you have further questions, let me know.

**Comment by AlexanderZeilmann** [comment]
Thank you, this clarifies things!

> I am planning to move larsgw/citation.js to something like citation-js/classic and updating the README to clarify, but I have been putting it off because I'm worried I would mess the situation up even further.

My suggestion would be to
* not move `larsgw/citation.js`, but leave it where it is. Moving will probably create more confusion.
* add a note to `larsgw/citation.js` saying that people should use `citation-js/citation-js`,
* Fix the website to point to `citation-js/citation-js` (I can send a pull request if you want)
