### ISSUE TITLE
Are there some CSL templates that don't work with citeproc?

### ISSUE THREAD

**Issue by cclpeng** [citation-js/citation-js#189]
I'm trying to get different CSL templates from zotero's library, with "https://zotero.org/styles/ieee" or /topoi, and for some common citation styles like 'modern-language-association-7th-edition', 'ieee', 'chicago-author-date', I think creating the bibliography is working.

However, when I try with some styles "topoi", "cytokine", "applied-informatics" (and all other styles I've tried so far), then citeproc_commonjs.js's makeBibliography() returns false, and it won't be able to make the bibliography. 

from this file: webpack:///node_modules/@citation-js/plugin-csl/lib-mjs/bibliography.js
citation-js tries to get information from the citeproc's makeBibliography() function but the returned data isn't in the right structure
``` 
const bibliography = citeproc.makeBibliography(); 
const [{
    bibstart,
    bibend
}, bibBody] = bibliography;
```
 This part fails because makeBibliography() returns false instead of an array object, and then the error in the console is 
```
 Uncaught (in promise) TypeError: Invalid attempt to destructure non-iterable instance.
In order to be iterable, non-array objects must have a [Symbol.iterator]() method.
    at _nonIterableRest (attr.js:3:1)
```

from this file: webpack:///node_modules/citeproc/citeproc_commonjs.js,
the citeproc makeBibliography() returns false because of this line 
```
// API change: added in version 1.0.51
    if (!this.bibliography.tokens.length) {
        return false;
    }
```
I saw that when the template was "ieee", it would have about four hundred tokens (that seem related to making a bibliography), but when it was "topoi", there were 0 tokens. 
    
    
Do you know if anything I detailed here shows I'm doing something wrong? I can show what the csl template strings look like in the registry at the time too
![image](https://user-images.githubusercontent.com/17967931/215622592-e14bbf6b-da6e-417e-a493-8ffc164e3d06.png)

and here is the topoi csl file I got from the zotero API call, which I noticed is a lot shorter than the mla/ apa templates.
```
<?xml version="1.0" encoding="utf-8"?>
<style xmlns="http://purl.org/net/xbiblio/csl" version="1.0" default-locale="en-US">
  <!-- Generated with https://github.com/citation-style-language/utilities/tree/master/generate_dependent_styles/data/springer -->
  <info>
    <title>Topoi</title>
    <title-short>Topoi</title-short>
    <id>http://www.zotero.org/styles/topoi</id>
    <link href="http://www.zotero.org/styles/topoi" rel="self"/>
    <link href="http://www.zotero.org/styles/springer-basic-author-date" rel="independent-parent"/>
    <link href="http://www.springer.com/cda/content/document/cda_downloaddocument/Key_Style_Points_1.0.pdf" rel="documentation"/>
    <link href="http://www.springer.com/cda/content/document/cda_downloaddocument/manuscript-guidelines-1.0.pdf" rel="documentation"/>
    <category citation-format="author-date"/>
    <category field="science"/>
    <issn>0167-7411</issn>
    <eissn>1572-8749</eissn>
    <updated>2014-05-18T01:40:32+00:00</updated>
    <rights license="http://creativecommons.org/licenses/by-sa/3.0/">This work is licensed under a Creative Commons Attribution-ShareAlike 3.0 License</rights>
  </info>
</style>
```

**Comment by larsgw** [comment]
I keep forgetting about this yes. The styles that you link that do not work are [dependent styles](https://docs.citationstyles.org/en/stable/specification.html#dependent-styles) that only\* provide an alias for a different style. In this case, the `topoi` style is an alias for `springer-basic-author-date` (see the `<link>` element with `rel="independent-parent"`). citeproc-js does not handle this as far as I know, and it would be difficult to handle in Citation.js since it has to synchronously, dynamically fetch an online resource in a plugin that otherwise never does so. What Citation.js could at the very least do is throw a good error message. What you can do for Topoi specifically is use the `springer-basic-author-date` style directly, or in general parse the XML and look for `rel="independent-parent"`.

\* Dependent styles can also override certain locale settings. Topoi does not use this but others might, and I do not know how to simulate this behavior without changing citeproc-js.

**Comment by cclpeng** [comment]
Wow thank you so much! This was very helpful. Yes I can check myself if it is dependent or not.
