### ISSUE TITLE
Fields for citing translation are not in CSL-JSON

### ISSUE THREAD

**Issue by crystalfp** [citation-js/citation-js#198]
I need to cite the translation of another book in the bibliography.

Besides how to do this on the BibLaTeX side, there are fields that don't came through `plugin-bibjson` but are valid (according to [CTAN biblatex package](http://mirrors.ctan.org/macros/latex/contrib/biblatex/doc/biblatex.pdf)). They are: `series`, `crossref` and `addendum`. These fields are listed in `constants.fieldTypes` but do not appear in the CSL-JSON output. Also in `note` the `\cite{Valle2017}` is transformed to `citeValle2017`.

For now, I solved my problem by simply expanding the citation in the note field, so consider this as a feature request.

Thanks!
			mario

```
@Book{Valle2017,
  author    = {Mario Valle},
  publisher = {il leone verde},
  title     = {{La pedagogia Montessori e le nuove tecnologie}},
  year      = {2017},
  isbn      = {978-88-6580-174-1},
  series    = {Appunti Montessori},
}

@Book{Valle2019,
  author     = {Mario Valle},
  publisher  = {LIT Verlag},
  title      = {{Montessori-Pädagogik und neue Technologien. Eine mögliche Integration?}},
  year       = {2019},
  isbn       = {978-3-643-14265-8},
  note       = {German translation of \cite{Valle2017}},
  series     = {Impulse der Reformpädagogik},
  translator = {Wolfgang Wedekind},
  crossref   = {Valle2017},
  addendum   = {German translation of: \fullcite{Valle2017}}
}
```

**Comment by larsgw** [comment]
- `series` does appear (in the CSL-JSON field `collection-title`) but it is the German series.
- The `crossref` is resolved (i.e. the data inheritance rules are applied) instead of keeping the field, as it has no equivalent in CSL-JSON. As `Valle2019` already contains a `series` field, the `series` field of `Valle2017` is ignored. Even if it weren't, CSL-JSON has no field (yet) for `original-collection-title`, so the value would be lost when mapping it to CSL-JSON anyway.
- `addendum` should be mapped to CSL-JSON `note` in the future, though in this case the BibTeX `note` field would have priority.
- I do not think I can add full support for `\cite{}` and `\fullcite{}`, as it would require a large dependency (`@citation-js/plugin-csl` and `citeproc-js`) and two passes over the input, but you can define them yourself:

    ```js
    const { plugins } = require('@citation-js/core')

    const config = plugins.config.get('@bibtex')
    config.constants.argumentCommands.cite = function (key) {
      // ...
    }
    ```

    You could for example do something like this:

    ```js
    const { Cite, plugins } = require('@citation-js/core')
    require('@citation-js/plugin-bibtex')
    require('@citation-js/plugin-csl')

    const cache = new Cite()

    const config = plugins.config.get('@bibtex')
    config.constants.argumentCommands.cite = function (key) {
      const inCache = cache.data.some(entry => entry['citation-key'] === key)
      return inCache ? cache.format('citation', { entry: key }) : `(missing: ${key})`
    }

    cache.add(input)

    // new Cite(input) etc.
    ```

**Comment by crystalfp** [comment]
Thanks a lot, @larsgw ! Very useful. Sure, I have to read carefully the crossref rules.
