### ISSUE TITLE
TypeError: Cannot read property 'toLowerCase' of undefined

### ISSUE THREAD

**Issue by huanfachen** [citation-js/citation-js#99]
Hi all. I would like to transform a bibjson file into a .bib file, but have the following error:

> TypeError: Cannot read property 'toLowerCase' of undefined
>     at getPrefixedOptions (C:\Users\Huanfa Chen\AppData\Roaming\npm\node_modules\citation-js\node_modules\@citation-js\cli\lib\index.js:198:28)
>     at processInput (C:\Users\Huanfa Chen\AppData\Roaming\npm\node_modules\citation-js\node_modules\@citation-js\cli\lib\index.js:176:40)
>     at main (C:\Users\Huanfa Chen\AppData\Roaming\npm\node_modules\citation-js\node_modules\@citation-js\cli\lib\index.js:74:29)

The bibjson file is [rfpimp.txt](https://github.com/citation-js/citation-js/files/5118342/rfpimp.txt).

and the command that I used is

`citation-js -i rfpimp.txt -o rfpimp.bib -s bibtex`

Environment: 

- Windows 10, X64, command-line.

- citation.js: 0.5.0-alpha.6

Many thanks for your suggestions.

**Comment by larsgw** [comment]
Thank you for taking the time to report this! It's weird to me that I did not encounter this issue before. Get this running by:

  1. Piping the input to stdin (the `-i/--input` flag is what breaks things)
  2. Remove the `.bib` file extension (it adds that by default)
  3. Add `-f string` to get actual BibTeX instead of a JSON representation

I think on Windows that results in

    citation-js < rfpimp.txt -o rfpimp -s bibtex -f string

If you ever want output with a different file extension redirecting stdout should work

    citation-js < rfpimp.txt > rfpimp.bib -s bibtex -f string
